language: cpp
compiler:
- gcc

os:
- linux
- osx


before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo add-apt-repository ppa:team-xbmc/ppa -y; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get update -qq; fi

- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:


- if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get install libsdl2-dev; fi


- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2; fi

before_script:

- mkdir Build
- cd Build
- cmake -D CMAKE_BUILD_TYPE=Release ..

script:

- cmake --build . --target ALL_BUILD --config Release
- cmake --build . --target package --config Release




