
os: Visual Studio 2015


install:

# SDL2
- IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-2.0.4-VC.zip appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
- dir
- 7z x SDL2-devel-2.0.4-VC.zip -o.\Extern\
- cd Extern
- dir
- cd ..

cache:

- SDL2-devel-2.0.4-VC.zip


build_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" ..

- cmake --build . --target ALL_BUILD --config Release
- cmake --build . --target package --config Release



artifacts:
  - path: build\_CPack_Packages\win64\*.zip
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: GSeHA5oScu2V+7ZcApcnd6v0JtUT1IVvYajvHtX2r7+NtaChQJuObULDFvFLZ4Ul
  artifact: /*.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true