#ifndef __CONFIG_H__
#define __CONFIG_H__

//WARNING This file is generated by CMake

#define GIT_DESCRIBE_VERSION "0.1.1"

#define VERSION_MAJOR "0"
#define VERSION_MINOR "1"
#define VERSION_PATCH "1"

#endif
