#ifndef __CONFIG_H__
#define __CONFIG_H__

//WARNING This file is generated by CMake

#define GIT_DESCRIBE_VERSION "0.1.9-1-g369355d"

#define VERSION_MAJOR "0"
#define VERSION_MINOR "1"
#define VERSION_PATCH "9"



#ifndef TARGET_WIN32
#define TARGET_WIN32
#endif

#ifndef TARGET_LINUX
/* #undef TARGET_LINUX */
#endif

#ifndef TARGET_OSX
/* #undef TARGET_OSX */
#endif

#endif
